apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app-deployment
spec:
  selector:
    matchLabels:
      app: fastapi-app
  replicas: 1
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      volumes:
        - name: envoy
          configMap:
            name: envoy-config
      containers:
        - name: api
          image: tadadadada/fastapi-app:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
        - name: envoy
          image: envoyproxy/envoy:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: envoy
              mountPath: /etc/envoy
          command:
            - "/usr/local/bin/envoy"
          args:
            - "--config-path /etc/envoy/envoy.yaml"
          ports:
            - containerPort: 10000
              name: envoy-sidecar
            - containerPort: 10001
              name: envoy-admin
